# You can enable or disable the alerts when a player join with an alt or from a seen country.
onJoin alert: true

# With this limit, you can let a player have some alts without cause any alert on player who has the "fraud.receive.alert" permission.
# Set to -1 to untoggle this limit.
# Default is 2
alts limit: 2

# Set this to false to no longer receive an alert offering you to post a review on the plugin's spigot page.
ask for review: false

update:
  # If this is true, every 5 minutes, a check will be made to see if the plugin is up to date.
  # If it is not up-to-date, a message will be sent to all players with the permission "fraud.update".
  check for update: true
  auto download: false
  
kick:
  # If this is set to enabled, if it is set that the player has too much double count, he will be kick.
  enabled: false
  # The number of alts to trigger the kick is adjustable on "alts limit" on line 7.
  # {0} is the number of accounts on the ip. | \n is used to returned to the line.
  kick reason: "§f§lThe server has detected that you have too many accounts on your ip §7§l({0} accounts)§f§l.\n§f§lYou can not log in with as much of an account as that!\n§f§lContact an administrator if you think this is an error."

# A player who joins the server and who does not come from his country will cause an alert to players who have the "fraud.receive.alert.location" permissions.
# Set '*' to disable the countries alert.
# If the global alerts, it will not cause any alert even theses.
countries alert:
  - "FR"
  - "BE"
  - "CH"
  - "CA"
  - "MR"
  - "MC"
  - "DZ"
  - "MA"

# |---------------------------------------------------------------------|
# | These messages accept the chat color format with the '&' character. |
# |---------------------------------------------------------------------|
messages:
  prefix: " &6&lFraud &7» &e"
  no permission: "&cSorry but you can''t do that. You don''t have the permission!"
  # {0} is the name of the player/ip | {1} is the country of the player
  bad country detected: "&6{0} &ccomes from a suspicious country: &6{1}"
  # {0} is the name of the player/ip | {1} is the list of alts
  alts detected: "&cSome double-accounts where been detected in the account of &6{0}&c, here there are:\n&r{1}"
  alts asked: "&cHere is the list of alts of &6{0}&c:\n{1}"
  all alts announcer: "&cHere is the list of alts of all connected players:"
  all alts asked: "  &6{0}&c:\n      {1}"
  all alts empty: "&cThere is no players connected who has alts."
  info:
    hover: "&6Click to get more information&6."
    wait_for_the_other_part: "&7&oPlease wait for the information part about the ip..."
    # {0} is the name of the player | {1} is the ip of the player
    header: "&cHere is the information about the alts of &6{0}&c:"
    header_ip: "&cHere is the information about the alts of &6{0}&e&o({1})&c:"
    # {0} is the name of the player | {1} is the first join | {2} is the last join
    player: "  &c- &6{0}&c:\n     &c• First Join: &6{1}\n     &c• Last Join: &6{2}"
    # {0} is the ip of the player | {1} is the country of the ip | {2} is the others Informations
    ip_information: "&cHere is the informations about the ip &6{0}&c:\n  &c• Country: &6{1}\n  &c• Others Informations: &6{2}"
  # {0} is the name of the player.
  no alts: "&6{0}&c never connected double accounts."
  not in datas: "&6{0}&c isn''t in the files."
  player forgotten: "&6{0} has been removed of the files."
  reload:
    success: "&cReload success."
    failed: "&cReload failed. &oStacktrace print in console."
  alert:
    # DO NOT REMOVE THE "_" CHAR.
    on_: "&aYou''ll now receive the connections alerts."
    off_: "&cYou''ll no longer receive the connections alerts."
  help:
    command:
      # {0} is the label of the command. Ex: "fraud", "fd" It can change if you use some alias of the command.
      all: "&f&l/{0} all &7- Check all players about alts / double-accounts."
      alert: "&f&l/{0} alert &7- Disables connection alerts."
      check: "&f&l/{0} check <player> &7- Check if a player have some alts / double-accounts."
      contact: "&f&l/{0} contact &7- Contact me if you have any problem, plugin error or requests."
      download: "&f&l/{0} (download|dl) &7- Download the latest version of the plugin (must be restart after this)."
      forgot: "&f&l/{0} forgot <player> &7- Remove all the datas about this player. &8&o&n(WARNING: this is not cancellable)."
      info: "&f&l/{0} info <player> &7- Give some info about the connection of a player."
      link: "&f&l/{0} links &7- Give some links about the plugin(Source-code, Spigot, Direct Download)."
      reload: "&f&l/{0} reload &7- Reload the configuration and data files."
      version: "&f&l/{0} (version|checkupdate|v) &7- Give the version of the plugin."
  time:
    and: "and"
    now: "now"
    year: "year"
    years: "years"
    month: "month"
    months: "months"
    day: "day"
    days: "days"
    hour: "hour"
    hours: "hours"
    minute: "minute"
    minutes: "minutes"
    second: "second"
    seconds: "seconds"