name: Fraud
author: Rgld_
version: 1.2
description: Detects if a player is fraudding the server.
website: https://github.com/R-Gld/Fraud

softdepend:
  - PlugMan

main: fr.Rgld_.Fraud.Fraud
commands:
  fraud:
    description: This command is the only one of the "Fraud" plugin. It allows to know if players have connected with double accounts.
    aliases:
      - fd
      - alts
      - double-accounts

permissions:
  # Global permissions
  fraud.*:
    description: Give all the permission of the plugin Fraud.
    default: op
    children:
      fraud.bypass.*: true
      fraud.check.*: true
      fraud.notcause.alert: true
      fraud.receive.alert: true
      fraud.clean-datas: true
      fraud.reload: true
      fraud.update: true
  fraud.bypass.*:
    description: Give all the bypass available
    default: op
    children:
      fraud.bypass.ip: true
      fraud.bypass.alert: true
  fraud.check.*:
    description: Give all the check permissions.
    default: op
    children:
      fraud.check.player: true
      fraud.check.ip: true
  fraud.check.player:
    description: Give all the check permissions for players.
    default: op
    children:
      fraud.check.player.one: true
      fraud.check.player.all: true

  # Basic permissions
  fraud.bypass.ip:
    default: op
    description: If a player have this permission, his ip is not registered on the data's file(can be disabled by config).
  fraud.bypass.alert:
    default: op
    description: If a player have this permission, there will never be a double-count alert about it.
  fraud.notcause.alert:
    default: op
    description: The players who has the permission "fraud.receive.alert" never receive an alert from this player if the number of his alts is below the limit defined in the config.
  fraud.receive.alert:
    default: op
    description: When a player join for the first time the server, all the player who has this permission will receive a message if this player have a alt.
  fraud.check.player.one:
    default: op
    description: Let a player check if an other player has some alts.
  fraud.check.player.all:
    default: op
    description: Let a player check if all players has some alts.
  fraud.check.ip:
    default: op
    description: Let a player check if an ip has some alts.
  fraud.clean-datas:
    default: op
    description: Let a player to reset the datas.
  fraud.reload:
    default: op
    description: Let a player to reload the configuration and datas files.
  fraud.update:
    default: op
    description: Let a player update the plugin.