name: Fraud
author: Rgld_
version: 1.7.1 # Only chars accepted for the version: "0123456789."
description: Detects if a player is fraudding the server.
website: https://www.spigotmc.org/resources/fraud-alts-finder.69872/
main: fr.Rgld_.Fraud.Fraud

commands:
  fraud:
    description: This command is the only one of the "Fraud" plugin. It allows to know if players have connected with double accounts.
    aliases:
      - fd
      - alts

permissions:
  # Group Permissions
  fraud.*:
    description: Give all the permission of the plugin Fraud.
    default: op
    children:
      fraud.bypass.*: true
      fraud.check.*: true
      fraud.notcause.alert: true
      fraud.receive.alert: true
      fraud.clean-datas: true
      fraud.reload: true
      fraud.update: true
      fraud.download: true
      fraud.forgot: true
  fraud.bypass.*:
    description: Give all the bypass available
    default: op
    children:
      fraud.bypass.ip: true
      fraud.bypass.alert: true
  fraud.check.*:
    description: Give all the check permissions.
    default: op
    children:
      fraud.check.player: true
      fraud.check.ip: true
      fraud.info: true
  fraud.check.player:
    description: Give all the check permissions for players.
    default: op
    children:
      fraud.check.player.one: true
      fraud.check.player.all: true
  
  # Basic Permissions
  fraud.bypass.ip:
    default: op
    description: If a player have this permission, his ip is not registered on the data's file(can be disabled by config).
  fraud.bypass.alert:
    default: op
    description: If a player have this permission, there will never be a double-count alert about it.
  fraud.notcause.alert:
    default: op
    description: The players who has the permission "fraud.receive.alert" never receive an alert from this player if the number of his alts is below the limit defined in the config.
  fraud.receive.alert:
    default: op
    description: When a player join for the first time the server, all the player who has this permission will receive a message if this player have a alt.
  fraud.alert.switch:
    default: op
    description: Allows someone who receives the alerts to disable them. (/fd alert)
  fraud.check.player.one:
    default: op
    description: Let a player check if an other player has some alts.
  fraud.check.player.all:
    default: op
    description: Let a player check if all players has some alts.
  fraud.check.ip:
    default: op
    description: Let a player check if an ip has some alts.
  fraud.clean-datas:
    default: op
    description: Let a player to reset the datas.
  fraud.reload:
    default: op
    description: Let a player to reload the configuration and datas files.
  fraud.update:
    default: op
    description: Let a player update the plugin.
  fraud.download:
    default: op
    description: Let a player download the latest version of the plugin on spigot.
  fraud.info:
    default: op
    description: Let a player execute the /fd info.
  fraud.forgot:
    default: op
    description: Let a player delete an entry into the database.
