# Toggle alerts for when a player joins using an alternate account or from a recognized country. (true = enabled, false = disabled)
onJoin alert: true

# Limit the number of alternate accounts a player can have without triggering an alert for users with "fraud.receive.alert" permission. Set to -1 to remove the limit. Default: 2
alts limit: 2

# Disable or enable requests for reviewing the plugin on the Spigot page. (false = no requests, true = requests enabled)
ask for review: false

# Enable or disable GeoIP functionality, which provides approximate location data of players. Disabling it will still allow country connection information to be available. (true = enabled, false = disabled)
geoip-enable: true

# Choose the type of data storage (sqlite or (mysql/mariadb). If 'mysql'(or 'mariadb' is chosen, additional parameters (ip, port, user, password, database) must be specified.
data store:
  type: sqlite
  #type: mysql
  #parameters:
  #  ip: "localhost"
  #  port: 3306
  #  user: "fraud"
  #  password: "password"
  #  database: "Fraud"

update:
  # Check for plugin updates every 5 minutes and notify players with "fraud.update" permission if an update is available. (true = enabled, false = disabled)
  check for update: true
  # Toggle automatic downloading of updates. (true = enabled, false = disabled)
  auto download: false

kick:
  # Enable or disable kicking players who exceed the alt account limit. (true = enabled, false = disabled)
  enabled: false
  # Message displayed when a player is kicked for exceeding the alt account limit. '{0}' represents the number of accounts from the same IP. '\n' is used for line breaks.
  kick reason: "§f§lThe server has detected that you have too many accounts on your ip §7§l({0} accounts)§f§l.\n§f§lYou can not log in with as much of an account as that!\n§f§lContact an administrator if you think this is an error."

# Alert players with "fraud.receive.alert.location" permission when a player joins from a country different from their usual. Use '*' to disable country-specific alerts. Global alert settings override this.
countries alert:
  - "FR"
  - "BE"
  - "CH"
  - "CA"
  - "MR"
  - "MC"
  - "DZ"
  - "MA"
